[build]
  # Set the build command to run from the expressersweepstakes directory
  command = "cd expressersweepstakes && npm run build:netlify"
  # The directory where Netlify should look for the built files
  publish = "expressersweepstakes/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
